service: cs-group-${self:custom.stageVars.groupNumber}-${self:custom.stageVars.myFirstname}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: default

functions:
  hello:
    handler: functions/hello.handle
    events:
      - http:
          path: hello
          method: get

  goodbye:
    handler: functions/goodbye.handle
    events:
      - http:
          path: goodbye
          method: get

  list:
    handler: functions/list.handle
    events:
      - http:
          path: list
          method: get

custom:
  stageVars: ${file(./stage.${self:provider.stage}.yml)}
